"""add_tracking_tables

Revision ID: 202605db4657
Revises: d584a993cd99
Create Date: 2026-09-23 11:03:37.754491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202605db4657'
down_revision: Union[str, Sequence[str], None] = 'd584a993cd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_sessions_id'), 'tracking_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_is_active'), 'tracking_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_seller_id'), 'tracking_sessions', ['seller_id'], unique=False)
    op.create_table('location_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tracking_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_logs_id'), 'location_logs', ['id'], unique=False)
    op.create_index(op.f('ix_location_logs_recorded_at'), 'location_logs', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_location_logs_session_id'), 'location_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_logs_session_id'), table_name='location_logs')
    op.drop_index(op.f('ix_location_logs_recorded_at'), table_name='location_logs')
    op.drop_index(op.f('ix_location_logs_id'), table_name='location_logs')
    op.drop_table('location_logs')
    op.drop_index(op.f('ix_tracking_sessions_seller_id'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_is_active'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_id'), table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    # ### end Alembic commands ###
