"""add_phone_to_users_and_inquiry_tables

Revision ID: d584a993cd99
Revises: a1b2c3d4e5f6
Create Date: 2026-09-21 15:54:35.777126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd584a993cd99'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profile_id'), 'company_profile', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_ref_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('inquiry_date', sa.Date(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('factory_address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('ho_address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_ref_id'), 'customers', ['customer_ref_id'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_ref_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'contacted', 'completed', 'cancelled', name='inquiry_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_id'), 'inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_inquiries_inquiry_ref_id'), 'inquiries', ['inquiry_ref_id'], unique=True)
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_ref_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('concerned_person', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_id'), 'personnel', ['id'], unique=False)
    op.create_index(op.f('ix_personnel_personnel_ref_id'), 'personnel', ['personnel_ref_id'], unique=True)
    op.create_table('additional_inquiry_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('employee', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('local_import', sa.Enum('local', 'import_', name='local_import_enum'), nullable=True),
    sa.Column('new_repeat', sa.Enum('new', 'repeat', name='new_repeat_enum'), nullable=True),
    sa.Column('repeat_case_no', sa.String(), nullable=True),
    sa.Column('req_origin', sa.String(), nullable=True),
    sa.Column('incoterms', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('sub_department', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_additional_inquiry_info_id'), 'additional_inquiry_info', ['id'], unique=False)
    op.create_table('ccm_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('length_of_tube', sa.String(), nullable=True),
    sa.Column('manual_open_tanky', sa.String(), nullable=True),
    sa.Column('strands', sa.Integer(), nullable=True),
    sa.Column('cmt_size', sa.String(), nullable=True),
    sa.Column('sgm_size', sa.String(), nullable=True),
    sa.Column('tundish_nozzle_size', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_ccm_details_id'), 'ccm_details', ['id'], unique=False)
    op.create_table('furnace_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('no_of_furnaces', sa.Integer(), nullable=True),
    sa.Column('tpd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_furnace_details_id'), 'furnace_details', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_ref_id', sa.String(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('no_of_item', sa.Integer(), nullable=True),
    sa.Column('detailed_specifications', sa.Text(), nullable=True),
    sa.Column('required_model_number', sa.String(), nullable=True),
    sa.Column('picture_name_plate', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('application_usage', sa.Text(), nullable=True),
    sa.Column('installed_location', sa.String(), nullable=True),
    sa.Column('required_brand', sa.String(), nullable=True),
    sa.Column('new_replacement', sa.Enum('new', 'replacement', name='new_replacement_enum'), nullable=True),
    sa.Column('drawing', sa.String(), nullable=True),
    sa.Column('layout', sa.String(), nullable=True),
    sa.Column('existing_brand_or_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_ref_id'), 'products', ['product_ref_id'], unique=True)
    op.create_table('rolling_mill_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('plant_capacity_tpd', sa.Float(), nullable=True),
    sa.Column('plant_capacity_tph', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('total_stands', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_rolling_mill_details_id'), 'rolling_mill_details', ['id'], unique=False)
    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('unisons_sales_rep', sa.String(), nullable=True),
    sa.Column('customer_signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_signatures_id'), 'signatures', ['id'], unique=False)
    op.create_table('special_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_special_instructions_id'), 'special_instructions', ['id'], unique=False)
    op.create_table('furnaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('furnace_ref_id', sa.String(), nullable=False),
    sa.Column('furnace_details_id', sa.Integer(), nullable=False),
    sa.Column('furnace_no', sa.String(), nullable=True),
    sa.Column('capacity_ton', sa.Float(), nullable=True),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['furnace_details_id'], ['furnace_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furnaces_furnace_ref_id'), 'furnaces', ['furnace_ref_id'], unique=True)
    op.create_index(op.f('ix_furnaces_id'), 'furnaces', ['id'], unique=False)
    op.create_table('rolling_mill_stands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stand_ref_id', sa.String(), nullable=False),
    sa.Column('rolling_mill_id', sa.Integer(), nullable=False),
    sa.Column('mill_type', sa.Enum('fully_continuous', 'roughing_mill', 'intermediate_mill', 'finishing_mill', name='mill_type_enum'), nullable=True),
    sa.Column('stand_code', sa.Enum('RM1', 'RM2', 'RM3', 'IM1', 'IM2', 'IM3', 'FM1', 'FM2', 'FM3', name='stand_code_enum'), nullable=True),
    sa.Column('arrangement_type', sa.Enum('repeater', 'continuous', 'fully_continuous', name='arrangement_type_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rolling_mill_id'], ['rolling_mill_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolling_mill_stands_id'), 'rolling_mill_stands', ['id'], unique=False)
    op.create_index(op.f('ix_rolling_mill_stands_stand_ref_id'), 'rolling_mill_stands', ['stand_ref_id'], unique=True)
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_rolling_mill_stands_stand_ref_id'), table_name='rolling_mill_stands')
    op.drop_index(op.f('ix_rolling_mill_stands_id'), table_name='rolling_mill_stands')
    op.drop_table('rolling_mill_stands')
    op.drop_index(op.f('ix_furnaces_id'), table_name='furnaces')
    op.drop_index(op.f('ix_furnaces_furnace_ref_id'), table_name='furnaces')
    op.drop_table('furnaces')
    op.drop_index(op.f('ix_special_instructions_id'), table_name='special_instructions')
    op.drop_table('special_instructions')
    op.drop_index(op.f('ix_signatures_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_rolling_mill_details_id'), table_name='rolling_mill_details')
    op.drop_table('rolling_mill_details')
    op.drop_index(op.f('ix_products_product_ref_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_furnace_details_id'), table_name='furnace_details')
    op.drop_table('furnace_details')
    op.drop_index(op.f('ix_ccm_details_id'), table_name='ccm_details')
    op.drop_table('ccm_details')
    op.drop_index(op.f('ix_additional_inquiry_info_id'), table_name='additional_inquiry_info')
    op.drop_table('additional_inquiry_info')
    op.drop_index(op.f('ix_personnel_personnel_ref_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_id'), table_name='personnel')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_inquiries_inquiry_ref_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_ref_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_company_profile_id'), table_name='company_profile')
    op.drop_table('company_profile')
    # ### end Alembic commands ###
